MODULE GETDATA_MOD

USE OMP_LIB
USE PARKIND1

INTERFACE REPLICATE
  MODULE PROCEDURE REPLICATE1
  MODULE PROCEDURE REPLICATE2
END INTERFACE

INTERFACE NPROMIZE
  MODULE PROCEDURE NPROMIZE2
  MODULE PROCEDURE NPROMIZE3
END INTERFACE

CONTAINS

SUBROUTINE GETDATA (CDCASE, NPROMA, NGPBLKS, &
PAPRS_B, PAPRSF_B, PDELP_B, PNBVNO_B, PRDELP_B, PU_B, PV_B, PRCORI_B, PGETRL_B, PGWDCS_B, PVRLAN_B, PVRLDI_B, &
PSTRDU_B, PSTRDV_B, PRAPTRAJ_B, &
& LDVERBOSE)


USE IEEE_ARITHMETIC, ONLY : IEEE_SIGNALING_NAN, IEEE_VALUE

IMPLICIT NONE

INTEGER, PARAMETER :: IFILE = 77

CHARACTER (LEN=*) :: CDCASE

INTEGER      :: NPROMA, NGPBLKS
INTEGER      :: KLON 
INTEGER      :: KIDIA  
INTEGER      :: KFDIA  
INTEGER      :: KLEV  

REAL(KIND=JPRB), ALLOCATABLE :: PAPRS_B(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PAPRSF_B(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PDELP_B(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PNBVNO_B(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRDELP_B(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PU_B(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PV_B(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRCORI_B(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PGETRL_B(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PGWDCS_B(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PVRLAN_B(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PVRLDI_B(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PSTRDU_B(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PSTRDV_B(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRAPTRAJ_B(:,:,:) 

REAL(KIND=JPRB), ALLOCATABLE :: PAPRS(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PAPRSF(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PDELP(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PNBVNO(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRDELP(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PU(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PV(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRCORI(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PGETRL(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PGWDCS(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PVRLAN(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PVRLDI(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PSTRDU(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PSTRDV(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRAPTRAJ(:,:,:) 

LOGICAL :: LDVERBOSE


LOGICAL :: LLEXIST
CHARACTER(LEN=32) :: CLFILE
INTEGER :: ILUN, ILUNI, ILUNO, NGPTOT, IOFF, IBL
REAL (KIND=JPRB) :: ZNAN

NGPTOT = NPROMA * NGPBLKS

ILUN = 77

OPEN (ILUN, FILE=TRIM (CDCASE)//'/ACDRAG.DIMS.dat', FORM='UNFORMATTED', STATUS='OLD')
READ (ILUN) KLON, KLEV, KIDIA
CLOSE (ILUN)

ALLOCATE (PAPRS_B(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PAPRSF_B(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PDELP_B(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PNBVNO_B(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PRDELP_B(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PU_B(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PV_B(NPROMA,KLEV,NGPBLKS) )
ALLOCATE (PRCORI_B(NPROMA,NGPBLKS) )
ALLOCATE (PGETRL_B(NPROMA,NGPBLKS) )
ALLOCATE (PGWDCS_B(NPROMA,NGPBLKS) )
ALLOCATE (PVRLAN_B(NPROMA,NGPBLKS) )
ALLOCATE (PVRLDI_B(NPROMA,NGPBLKS) )
ALLOCATE (PSTRDU_B(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PSTRDV_B(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PRAPTRAJ_B(NPROMA,0:KLEV,NGPBLKS) )

ZNAN = IEEE_VALUE (ZNAN, IEEE_SIGNALING_NAN)

PAPRS_B     = ZNAN
PAPRSF_B    = ZNAN
PDELP_B     = ZNAN
PNBVNO_B    = ZNAN
PRDELP_B    = ZNAN
PU_B        = ZNAN
PV_B        = ZNAN
PRCORI_B    = ZNAN
PGETRL_B    = ZNAN
PGWDCS_B    = ZNAN
PVRLAN_B    = ZNAN
PVRLDI_B    = ZNAN
PSTRDU_B    = ZNAN
PSTRDV_B    = ZNAN
PRAPTRAJ_B  = ZNAN

ALLOCATE (PAPRS(NGPTOT,0:KLEV,1))
ALLOCATE (PAPRSF(NGPTOT,KLEV,1))
ALLOCATE (PDELP(NGPTOT,KLEV,1))
ALLOCATE (PNBVNO(NGPTOT,0:KLEV,1))
ALLOCATE (PRDELP(NGPTOT,KLEV,1))
ALLOCATE (PU(NGPTOT,KLEV,1))
ALLOCATE (PV(NGPTOT,KLEV,1))
ALLOCATE (PRCORI(NGPTOT,1))
ALLOCATE (PGETRL(NGPTOT,1))
ALLOCATE (PGWDCS(NGPTOT,1))
ALLOCATE (PVRLAN(NGPTOT,1))
ALLOCATE (PVRLDI(NGPTOT,1))
ALLOCATE (PSTRDU(NGPTOT,0:KLEV,1))
ALLOCATE (PSTRDV(NGPTOT,0:KLEV,1))
ALLOCATE (PRAPTRAJ(NGPTOT,0:KLEV,1))

ILUNI = 77
ILUNO = 88

OPEN (ILUNI, FILE=TRIM (CDCASE)//'/ACDRAG.IN.dat',  FORM='UNFORMATTED', STATUS='OLD')
OPEN (ILUNO, FILE=TRIM (CDCASE)//'/ACDRAG.OUT.dat', FORM='UNFORMATTED', STATUS='OLD')

IOFF = 0
IBL = 1

DO 

  IF (IOFF+KLON > NGPTOT) THEN
    EXIT
  ENDIF

  READ (ILUNI, END=100) PAPRS(IOFF+1:IOFF+KLON,:,1)
  READ (ILUNI) PAPRSF(IOFF+1:IOFF+KLON,:,1)
  READ (ILUNI) PDELP(IOFF+1:IOFF+KLON,:,1)
  READ (ILUNI) PNBVNO(IOFF+1:IOFF+KLON,:,1)
  READ (ILUNI) PRDELP(IOFF+1:IOFF+KLON,:,1)
  READ (ILUNI) PU(IOFF+1:IOFF+KLON,:,1)
  READ (ILUNI) PV(IOFF+1:IOFF+KLON,:,1)
  READ (ILUNI) PRCORI(IOFF+1:IOFF+KLON,1)
  READ (ILUNI) PGETRL(IOFF+1:IOFF+KLON,1)
  READ (ILUNI) PGWDCS(IOFF+1:IOFF+KLON,1)
  READ (ILUNI) PVRLAN(IOFF+1:IOFF+KLON,1)
  READ (ILUNI) PVRLDI(IOFF+1:IOFF+KLON,1)

  READ (ILUNO) PSTRDU(IOFF+1:IOFF+KLON,:,1)
  READ (ILUNO) PSTRDV(IOFF+1:IOFF+KLON,:,1)
  READ (ILUNO) PRAPTRAJ(IOFF+1:IOFF+KLON,:,1)

  IOFF = IOFF + KLON

ENDDO

100 CONTINUE

CALL REPLICATE (IOFF, PAPRS(:,:,1))
CALL REPLICATE (IOFF, PAPRSF(:,:,1))
CALL REPLICATE (IOFF, PDELP(:,:,1))
CALL REPLICATE (IOFF, PNBVNO(:,:,1))
CALL REPLICATE (IOFF, PRDELP(:,:,1))
CALL REPLICATE (IOFF, PU(:,:,1))
CALL REPLICATE (IOFF, PV(:,:,1))
CALL REPLICATE (IOFF, PRCORI(:,1))
CALL REPLICATE (IOFF, PGETRL(:,1))
CALL REPLICATE (IOFF, PGWDCS(:,1))
CALL REPLICATE (IOFF, PVRLAN(:,1))
CALL REPLICATE (IOFF, PVRLDI(:,1))
CALL REPLICATE (IOFF, PSTRDU(:,:,1))
CALL REPLICATE (IOFF, PSTRDV(:,:,1))
CALL REPLICATE (IOFF, PRAPTRAJ(:,:,1))



CALL NPROMIZE (NPROMA, PAPRS        ,   PAPRS_B      )
CALL NPROMIZE (NPROMA, PAPRSF       ,   PAPRSF_B     )
CALL NPROMIZE (NPROMA, PDELP        ,   PDELP_B      )
CALL NPROMIZE (NPROMA, PNBVNO       ,   PNBVNO_B     )
CALL NPROMIZE (NPROMA, PRDELP       ,   PRDELP_B     )
CALL NPROMIZE (NPROMA, PU           ,   PU_B         )
CALL NPROMIZE (NPROMA, PV           ,   PV_B         )
CALL NPROMIZE (NPROMA, PRCORI       ,   PRCORI_B     )
CALL NPROMIZE (NPROMA, PGETRL       ,   PGETRL_B     )
CALL NPROMIZE (NPROMA, PGWDCS       ,   PGWDCS_B     )
CALL NPROMIZE (NPROMA, PVRLAN       ,   PVRLAN_B     )
CALL NPROMIZE (NPROMA, PVRLDI       ,   PVRLDI_B     )
CALL NPROMIZE (NPROMA, PSTRDU       ,   PSTRDU_B     )
CALL NPROMIZE (NPROMA, PSTRDV       ,   PSTRDV_B     )
CALL NPROMIZE (NPROMA, PRAPTRAJ     ,   PRAPTRAJ_B   )

END SUBROUTINE 

SUBROUTINE REPLICATE2 (KOFF, P)

INTEGER :: KOFF
REAL (KIND=JPRB)    :: P (:,:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I, :) = P (J, :)
ENDDO

END SUBROUTINE

SUBROUTINE REPLICATE1 (KOFF, P)

INTEGER :: KOFF
REAL (KIND=JPRB)    :: P (:)

INTEGER :: I, J

DO I = KOFF+1, SIZE (P, 1)
  J = 1 + MODULO (I - 1, KOFF)
  P (I) = P (J)
ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE2 (KPROMA, PI, PO)

INTEGER :: KPROMA
REAL (KIND=JPRB),  INTENT (IN)  :: PI (:,:) 
REAL (KIND=JPRB),  INTENT (OUT) :: PO (:,:)

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (PI, 2) /= 1) STOP 1

IGPTOT = SIZE (PI, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    PO (JLON, IBL) = PI (IGP + (JLON - 1), 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    PO (JLON, IBL) = PO (JFDIA, IBL)
  ENDDO

ENDDO

END SUBROUTINE

SUBROUTINE NPROMIZE3 (KPROMA, PI, PO)

INTEGER :: KPROMA
REAL (KIND=JPRB),  INTENT (IN)  :: PI (:,:,:) 
REAL (KIND=JPRB),  INTENT (OUT) :: PO (:,:,:)

INTEGER :: I, J, IGPBLK, IGPTOT, IGP, JLON, JIDIA, JFDIA

IF (SIZE (PI, 3) /= 1) STOP 1

IGPTOT = SIZE (PI, 1)
IGPBLK = 1 + (IGPTOT-1) / KPROMA

DO IGP = 1, IGPTOT, KPROMA
  IBL = 1 + (IGP - 1) / KPROMA
  JIDIA = 1
  JFDIA = MIN (KPROMA, IGPTOT - (IBL - 1) * KPROMA)

  DO JLON = JIDIA, JFDIA
    PO (JLON, :, IBL) = PI (IGP + (JLON - 1), :, 1)
  ENDDO

  DO JLON = JFDIA+1, KPROMA
    PO (JLON, :, IBL) = PI (JFDIA, :, IBL)
  ENDDO

ENDDO

END SUBROUTINE

END  MODULE
