MODULE LOAD_TCST_MOD

USE YOMCST, ONLY : TCST

INTERFACE LOAD
MODULE PROCEDURE LOAD_TCST
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TCST (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TCST), INTENT (OUT) :: YD

READ (KLUN) YD%RPI
READ (KLUN) YD%RCLUM
READ (KLUN) YD%RHPLA
READ (KLUN) YD%RKBOL
READ (KLUN) YD%RNAVO
READ (KLUN) YD%RDAY
READ (KLUN) YD%RDAYI
READ (KLUN) YD%RHOUR
READ (KLUN) YD%REA
READ (KLUN) YD%REPSM
READ (KLUN) YD%RSIYEA
READ (KLUN) YD%RSIDAY
READ (KLUN) YD%ROMEGA
READ (KLUN) YD%RA
READ (KLUN) YD%RG
READ (KLUN) YD%R1SA
READ (KLUN) YD%DEG2RAD
READ (KLUN) YD%RSIGMA
READ (KLUN) YD%RI0
READ (KLUN) YD%R
READ (KLUN) YD%RMD
READ (KLUN) YD%RMV
READ (KLUN) YD%RMO3
READ (KLUN) YD%RD
READ (KLUN) YD%RV
READ (KLUN) YD%RCPD
READ (KLUN) YD%RCPV
READ (KLUN) YD%RCVD
READ (KLUN) YD%RCVV
READ (KLUN) YD%RKAPPA
READ (KLUN) YD%RETV
READ (KLUN) YD%RMCO2
READ (KLUN) YD%RMCH4
READ (KLUN) YD%RMN2O
READ (KLUN) YD%RMCO
READ (KLUN) YD%RMHCHO
READ (KLUN) YD%RMNO2
READ (KLUN) YD%RMSO2
READ (KLUN) YD%RMSO4
READ (KLUN) YD%RMCFC11
READ (KLUN) YD%RMCFC12
READ (KLUN) YD%RMHCFC22
READ (KLUN) YD%RMCCL4
READ (KLUN) YD%RCW
READ (KLUN) YD%RCS
READ (KLUN) YD%RATM
READ (KLUN) YD%RTT
READ (KLUN) YD%RLVTT
READ (KLUN) YD%RLSTT
READ (KLUN) YD%RLVZER
READ (KLUN) YD%RLSZER
READ (KLUN) YD%RLMLT
READ (KLUN) YD%RDT
READ (KLUN) YD%RESTT
READ (KLUN) YD%RGAMW
READ (KLUN) YD%RBETW
READ (KLUN) YD%RALPW
READ (KLUN) YD%RGAMS
READ (KLUN) YD%RBETS
READ (KLUN) YD%RALPS
READ (KLUN) YD%RALPD
READ (KLUN) YD%RBETD
READ (KLUN) YD%RGAMD
END SUBROUTINE


END MODULE
