PROGRAM WRAP_ACDRAG

USE MODEL_PHYSICS_MF_MOD , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1  ,ONLY : JPIM     ,JPRB    ,JPRD
USE YOMCST   , ONLY : TCST

USE LOAD_TCST_MOD
USE LOAD_MODEL_PHYSICS_MF_TYPE_MOD
USE GETDATA_MOD
USE IEEE_ARITHMETIC, ONLY : IEEE_SIGNALING_NAN, IEEE_VALUE
USE XRD_GETOPTIONS


IMPLICIT NONE

TYPE(TCST)            :: YDCST
TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
INTEGER(KIND=JPIM)    :: KLON 
INTEGER(KIND=JPIM)    :: KLEV 
INTEGER(KIND=JPIM)    :: KIDIA 
INTEGER(KIND=JPIM)    :: KFDIA 
INTEGER(KIND=JPIM)    :: KTDIA 
REAL(KIND=JPRB), ALLOCATABLE :: PAPRS(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PAPRSF(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PDELP(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PNBVNO(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRDELP(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PU(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PV(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRCORI(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PGETRL(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PGWDCS(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PVRLAN(:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PVRLDI(:,:) 

REAL(KIND=JPRB), ALLOCATABLE :: PSTRDU(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PSTRDV(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRAPTRAJ(:,:,:) 

REAL(KIND=JPRB), ALLOCATABLE :: PSTRDU_R(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PSTRDV_R(:,:,:) 
REAL(KIND=JPRB), ALLOCATABLE :: PRAPTRAJ_R(:,:,:) 

#include "acdrag.intfb.h"

INTEGER :: ILUN, NPROMA, NGPBLKS, IBL, JLEV
LOGICAL :: LLVERBOSE, LLCHECK
CHARACTER*32 :: CLCASE
REAL (KIND=JPRB) :: ZNAN


CALL INITOPTIONS ()
NGPBLKS = 296 
CALL GETOPTION ("--blocks", NGPBLKS)
NPROMA = 32
CALL GETOPTION ("--nproma", NPROMA)
CALL GETOPTION ("--check",  LLCHECK)
CALL GETOPTION ("--case", CLCASE, MND=.TRUE.)
CALL CHECKOPTIONS ()





ZNAN = IEEE_VALUE (ZNAN, IEEE_SIGNALING_NAN)

ILUN = 77

OPEN (ILUN, FILE=TRIM (CLCASE)//'/ACDRAG.YDML_PHY_MF.dat', FORM='UNFORMATTED', STATUS='OLD'); CALL LOAD (ILUN, YDML_PHY_MF); CLOSE (ILUN)
OPEN (ILUN, FILE=TRIM (CLCASE)//'/ACDRAG.YDCST.dat',       FORM='UNFORMATTED', STATUS='OLD'); CALL LOAD (ILUN, YDCST      ); CLOSE (ILUN)
OPEN (ILUN, FILE=TRIM (CLCASE)//'/ACDRAG.DIMS.dat', FORM='UNFORMATTED', STATUS='OLD')
READ (ILUN) KLON, KLEV, KIDIA
CLOSE (ILUN)

KTDIA = 1

LLVERBOSE = .TRUE.

CALL GETDATA (CLCASE, NPROMA, NGPBLKS, &
PAPRS, PAPRSF, PDELP, PNBVNO, PRDELP, PU, PV, PRCORI, PGETRL, PGWDCS, PVRLAN, PVRLDI, &
PSTRDU_R, PSTRDV_R, PRAPTRAJ_R, &
& LLVERBOSE)

ALLOCATE (PSTRDU(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PSTRDV(NPROMA,0:KLEV,NGPBLKS) )
ALLOCATE (PRAPTRAJ(NPROMA,0:KLEV,NGPBLKS) )

PSTRDU   = ZNAN
PSTRDV   = ZNAN
PRAPTRAJ = ZNAN

DO IBL = 1, NGPBLKS

KIDIA = 1
KFDIA = NPROMA

CALL ACDRAG (YDCST, YDML_PHY_MF,KIDIA,KFDIA,NPROMA,KTDIA,KLEV &
& , PAPRS(:,:,IBL) , PAPRSF(:,:,IBL) , PDELP(:,:,IBL) , PNBVNO(:,:,IBL) &
& , PRDELP(:,:,IBL) , PU(:,:,IBL) , PV(:,:,IBL) , PRCORI(:,IBL) , PGETRL(:,IBL) &
& , PGWDCS(:,IBL) , PVRLAN(:,IBL) , PVRLDI(:,IBL) , PSTRDU(:,:,IBL) , PSTRDV(:,:,IBL) &
& , PRAPTRAJ(:,:,IBL) )

ENDDO

DO IBL = 1, NGPBLKS
  PRINT *, IBL

  PRINT *, " PSTRDU "
  DO JLEV = 1, KLEV
  WRITE (*, '(I6," ",100E20.12)') JLEV, PSTRDU   (:, JLEV, IBL)
  WRITE (*, '(I6," ",100E20.12)') JLEV, PSTRDU_R (:, JLEV, IBL)
  PRINT *
  ENDDO

ENDDO


END
