MODULE ACDRAG_SCC_MOD
CONTAINS
  SUBROUTINE ACDRAG_SCC (YDSTACK)
!$acc routine vector
    
    USE stack_mod
    
    IMPLICIT NONE
    TYPE(STACK), INTENT(IN) :: YDSTACK
    TYPE(STACK) :: YLSTACK
    POINTER (IP, ZZ )
    REAL*8 :: ZZ (10)
    YLSTACK = YDSTACK
    IP = YLSTACK%L

    ZZ (1:10) = 3.14

  END SUBROUTINE ACDRAG_SCC
END MODULE ACDRAG_SCC_MOD
