MODULE COPY_MODEL_PHYSICS_MF_TYPE_MOD

USE MODEL_PHYSICS_MF_MOD, ONLY : MODEL_PHYSICS_MF_TYPE

INTERFACE COPY
MODULE PROCEDURE COPY_MODEL_PHYSICS_MF_TYPE
END INTERFACE

CONTAINS

SUBROUTINE COPY_MODEL_PHYSICS_MF_TYPE (YD)
USE COPY_SL_STRUCT_MOD
USE COPY_TARPHY_MOD
USE COPY_TCVMNH_MOD
USE COPY_TLOUIS_MOD
USE COPY_TMSE_MOD
USE COPY_TNORGWD_MOD
USE COPY_TPARAR_MOD
USE COPY_TPHY_MOD
USE COPY_TPHY0_MOD
USE COPY_TPHY1_MOD
USE COPY_TPHY2_MOD
USE COPY_TPHY3_MOD
USE COPY_TPHYDS_MOD
USE COPY_TSIMPHL_MOD
USE COPY_TTOPH_MOD
USE COPY_TVDOZ_MOD
IMPLICIT NONE
TYPE (MODEL_PHYSICS_MF_TYPE), INTENT (IN) :: YD

CALL COPY (YD%YRPHY)

CALL COPY (YD%YRPHY0)

CALL COPY (YD%YRPHY1)

CALL COPY (YD%YRPHY2)

CALL COPY (YD%YRPHY3)

CALL COPY (YD%YRPHYDS)

CALL COPY (YD%YRCVMNH)

CALL COPY (YD%YRTOPH)

CALL COPY (YD%YRVDOZ)

CALL COPY (YD%YRSIMPHL)

CALL COPY (YD%YRARPHY)

CALL COPY (YD%YRPARAR)

CALL COPY (YD%YRMSE)

CALL COPY (YD%YRLOUIS)

CALL COPY (YD%YRNORGWD)

CALL COPY (YD%YRGR)

END SUBROUTINE

END MODULE
