MODULE LOAD_TDVISI_MOD

USE YOMDVISI, ONLY : TDVISI

INTERFACE LOAD
MODULE PROCEDURE LOAD_TDVISI
END INTERFACE

CONTAINS

SUBROUTINE LOAD_TDVISI (KLUN, YD)

IMPLICIT NONE
INTEGER, INTENT (IN) :: KLUN
TYPE (TDVISI), INTENT (OUT) :: YD

READ (KLUN) YD%HVISI
READ (KLUN) YD%COEF_CM1
READ (KLUN) YD%COEF_CM2
READ (KLUN) YD%COEF_CM3
READ (KLUN) YD%COEF_CM4
READ (KLUN) YD%COEF_RM1
READ (KLUN) YD%COEF_RM2
READ (KLUN) YD%COEF_IM1
READ (KLUN) YD%COEF_IM2
READ (KLUN) YD%COEF_SM1
READ (KLUN) YD%COEF_SM2
READ (KLUN) YD%COEF_GM1
READ (KLUN) YD%COEF_GM2
END SUBROUTINE


END MODULE
