PROGRAM WRAP_ACDRAG
!SUBROUTINE WRAP_ACDRAG ()
  
  USE acdrag_SCC_MOD, ONLY: acdrag_SCC
  USE MODEL_PHYSICS_MF_MOD, ONLY: MODEL_PHYSICS_MF_TYPE
  USE PARKIND1, ONLY: JPIM, JPRB, JPRD
  USE YOMCST, ONLY: TCST
  
  USE LOAD_TCST_MOD
  USE LOAD_MODEL_PHYSICS_MF_TYPE_MOD
  USE GETDATA_MOD
  USE IEEE_ARITHMETIC, ONLY: IEEE_SIGNALING_NAN, IEEE_VALUE
  USE XRD_GETOPTIONS
  USE CHECK_UTILS_MOD
  USE stack_mod
  
#ifdef _MPI
  USE MPI
#endif
  
  
  
  IMPLICIT NONE
  
  TYPE(TCST) :: YDCST
  TYPE(MODEL_PHYSICS_MF_TYPE) :: YDML_PHY_MF
  INTEGER(KIND=JPIM) :: KLON
  INTEGER(KIND=JPIM) :: KLEV
  INTEGER(KIND=JPIM) :: KIDIA
  INTEGER(KIND=JPIM) :: KFDIA
  INTEGER(KIND=JPIM) :: KTDIA
  REAL(KIND=JPRB), ALLOCATABLE :: PAPRS(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PAPRSF(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PDELP(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PNBVNO(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PRDELP(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PU(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PV(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PRCORI(:, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PGETRL(:, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PGWDCS(:, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PVRLAN(:, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PVRLDI(:, :)
  
  REAL(KIND=JPRB), ALLOCATABLE :: PSTRDU(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PSTRDV(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PRAPTRAJ(:, :, :)
  
  REAL(KIND=JPRB), ALLOCATABLE :: PSTRDU_R(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PSTRDV_R(:, :, :)
  REAL(KIND=JPRB), ALLOCATABLE :: PRAPTRAJ_R(:, :, :)
  TYPE(STACK) :: my_stack_ptr
  REAL(KIND=JPRB), ALLOCATABLE :: my_stack_array(:, :)
  
  
  
  INTEGER :: ILUN, NPROMA, NGPBLKS, IBL, JLEV
  LOGICAL :: LLVERBOSE, LLCHECK
  CHARACTER(LEN=32) :: CLCASE
  REAL(KIND=JPRB) :: ZNAN
  REAL(KIND=8) :: start_time, end_time
  
  
  CALL INITOPTIONS()
  !NGPBLKS = 296
  CALL GETOPTION('--blocks', NGPBLKS)
  NPROMA = 32
  CALL GETOPTION('--nproma', NPROMA)
  CALL GETOPTION('--check', LLCHECK)
  CALL GETOPTION('--case', CLCASE, MND=.true.)
  CALL CHECKOPTIONS()
  
  
  
  
  
  ZNAN = IEEE_VALUE(ZNAN, IEEE_SIGNALING_NAN)
  
  ILUN = 77
  
  OPEN(UNIT = ilun, FILE = TRIM(clcase) // '/ACDRAG.YDML_PHY_MF.dat', FORM = 'UNFORMATTED', STATUS = 'OLD')
  CALL load(ilun, ydml_phy_mf)
  CLOSE(UNIT = ilun)
  OPEN(UNIT = ilun, FILE = TRIM(clcase) // '/ACDRAG.YDCST.dat', FORM = 'UNFORMATTED', STATUS = 'OLD')
  CALL load(ilun, ydcst)
  CLOSE(UNIT = ilun)
  OPEN(UNIT = ILUN, FILE = TRIM(CLCASE) // '/ACDRAG.DIMS.dat', FORM = 'UNFORMATTED', STATUS = 'OLD')
  READ(ILUN) KLON, KLEV, KIDIA
  CLOSE(UNIT = ILUN)
  
  KTDIA = 1
  
  ! LLVERBOSE = .TRUE.
  
  WRITE(*, *) "KLON = ", KLON, "    KLEV = ", KLEV
  WRITE(*, *) "NPROMA = ", NPROMA, "  NBLOCKS = ", NGPBLKS
  
  ALLOCATE (my_stack_array(100000*KLON, NGPBLKS))
  
  CALL GETDATA(CLCASE, NPROMA, NGPBLKS, PAPRS, PAPRSF, PDELP, PNBVNO, PRDELP, PU, PV, PRCORI, PGETRL, PGWDCS, PVRLAN, PVRLDI,  &
  & PSTRDU_R, PSTRDV_R, PRAPTRAJ_R, LLVERBOSE)
  
  ALLOCATE (PSTRDU(NPROMA, 0:KLEV, NGPBLKS))
  ALLOCATE (PSTRDV(NPROMA, 0:KLEV, NGPBLKS))
  ALLOCATE (PRAPTRAJ(NPROMA, 0:KLEV, NGPBLKS))
  
  PSTRDU = ZNAN
  PSTRDV = ZNAN
  PRAPTRAJ = ZNAN
  
#ifdef _MPI
  start_time = MPI_WTime()
#endif
  
  
!$acc parallel loop gang
  DO IBL=1,NGPBLKS
    
    my_stack_ptr%L = LOC(my_stack_array(1, IBL))
    my_stack_ptr%U = my_stack_ptr%L + KLON*100000*8
    
    KIDIA = 1
    KTDIA = 1
    KFDIA = NPROMA
    
    CALL ACDRAG_SCC(YDCST, YDML_PHY_MF, KIDIA, KFDIA, NPROMA, KTDIA, KLEV, PAPRS(:, :, IBL), PAPRSF(:, :, IBL),  &
    & PDELP(:, :, IBL), PNBVNO(:, :, IBL), PRDELP(:, :, IBL), PU(:, :, IBL), PV(:, :, IBL), PRCORI(:, IBL), PGETRL(:, IBL),  &
    & PGWDCS(:, IBL), PVRLAN(:, IBL), PVRLDI(:, IBL), PSTRDU(:, :, IBL), PSTRDV(:, :, IBL), PRAPTRAJ(:, :, IBL))
    
  END DO
!$acc end parallel loop
  
#ifdef _MPI
  end_time = MPI_WTime()
  WRITE(*, *) "Time in main loop = ", end_time - start_time
#endif
  
  
  
  !CALL SAVEDATA (CLCASE, NPROMA, NGPBLKS, KLEV, KLON, &
  !PSTRDU, PSTRDV, PRAPTRAJ)
  
  
  IF (LLCHECK == .true.) THEN
    WRITE(*, *) "================ CHECKING RESULTS ==============="
    
    WRITE(*, *) "check non zeroes on PSTRDU_R"
    CALL COUNT_ZEROES_NAN(PSTRDU_R, NPROMA*(KLEV + 1)*NGPBLKS)
    WRITE(*, *) "check non zeroes on PSTRDU"
    CALL COUNT_ZEROES_NAN(PSTRDU, NPROMA*(KLEV + 1)*NGPBLKS)
    
    WRITE(*, *) "check non zeroes on PSTRDV_R"
    CALL COUNT_ZEROES_NAN(PSTRDV_R, NPROMA*(KLEV + 1)*NGPBLKS)
    WRITE(*, *) "check non zeroes on PSTRDV "
    CALL COUNT_ZEROES_NAN(PSTRDV, NPROMA*(KLEV + 1)*NGPBLKS)
    
    WRITE(*, *) "check non zeroes on PRAPTRAJ_R"
    CALL COUNT_ZEROES_NAN(PRAPTRAJ_R, NPROMA*(KLEV + 1)*NGPBLKS)
    WRITE(*, *) "check non zeroes on PRAPTRAJ"
    CALL COUNT_ZEROES_NAN(PRAPTRAJ, NPROMA*(KLEV + 1)*NGPBLKS)
    
    WRITE(*, *) "check diff on PSTRDU"
    CALL COMPARE_VALUES(PSTRDU, PSTRDU_R, NPROMA*(KLEV + 1)*NGPBLKS)
    WRITE(*, *) "check diff on PSTRDV"
    CALL COMPARE_VALUES(PSTRDV, PSTRDV_R, NPROMA*(KLEV + 1)*NGPBLKS)
    WRITE(*, *) "check diff on PRAPTRAJ"
    CALL COMPARE_VALUES(PRAPTRAJ, PRAPTRAJ_R, NPROMA*(KLEV + 1)*NGPBLKS)
    
    WRITE(*, *) "================ CHECKING FINISHED ==============="
    
  END IF
  
  
  
!END SUBROUTINE WRAP_ACDRAG
END PROGRAM WRAP_ACDRAG
