PROGRAM WRAP_ACDRAG
  
!USE acdrag_SCC_MOD, ONLY: acdrag_SCC
!USE stack_mod
  
IMPLICIT NONE
  
TYPE STACK
  INTEGER*8 :: L, U
END TYPE

TYPE(STACK) :: YLSTACK
REAL(KIND=8), ALLOCATABLE :: ZSTACK (:, :)
INTEGER :: I

ALLOCATE (ZSTACK (32,10))
  
!!$ACC DATA CREATE(ZSTACK ) 
!$ACC ENTER DATA CREATE(ZSTACK )

!$acc parallel loop gang default(present) private(YLSTACK)
DO I=1, 10
    
  YLSTACK%L = LOC(ZSTACK (1, I))
  YLSTACK%U = YLSTACK%L + 32*8

  CALL ACDRAG_SCC (YLSTACK)
    
END DO
!$acc end parallel loop

CONTAINS

SUBROUTINE ACDRAG_SCC (YDSTACK)
!$acc routine vector
    
IMPLICIT NONE
TYPE(STACK), INTENT(IN) :: YDSTACK
TYPE(STACK) :: YLSTACK
POINTER (IP, ZZ )
REAL*8 :: ZZ (10)
YLSTACK = YDSTACK
IP = YLSTACK%L

ZZ (1:10) = 3.14

END SUBROUTINE ACDRAG_SCC
  
END PROGRAM WRAP_ACDRAG
